HAI
WAZZUP
I HAS A var ITZ "TEST"
I HAS A var2
I HAS A var4 ITZ var
BUHBYE
IM IN YR var UPPIN YR var1 TIL var2
VISIBLE "SOMETHING"
GTFO
IM OUTTA YR var
var2 R 123
GIMMEH var2
VISIBLE "AASDASD"
WTF?
OMG 1
GTFO
OMG 2
OMGWTF
VISIBLE "SOMETHING"
OIC
VISIBLE "SOMETHING ELSE"
HOW IZ I fun_name YR parameter1 AN YR parameter2
IF U SAY SO
I IZ function_name YR Exp_1 AN YR Exp_2 AN YR Exp_3 MKAY
KTHXBYE